import Head from "next/head";
import Articles from "../components/home/Articles";
import styles from "../styles/Home.module.css";
import { getAllPosts, PostMeta } from "../utils/markdown";

const Home = ({ posts }: { posts: PostMeta[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Articles</h1>
      <Articles posts={posts} />
    </div>
  );
};

export async function getStaticProps() {
  const posts = getAllPosts()
    .slice(0, 9)
    .map((post) => post.meta);

  return { props: { posts } };
}

export default Home;
