import Head from "next/head";
import { useState } from "react";
import HeroSection from "../components/home/HeroSection";
import MoreAboutMe from "../components/home/MoreAboutMe";
import MarkdownBlogCard from "../components/markdown/MarkdownBlogCard";
import { getAllPosts, PostMeta } from "../utils/markdown";
import { motion } from "framer-motion";

const Home = ({ posts }: { posts: PostMeta[] }) => {
  const [currentScreen, setCurrentScreen] = useState(1);

  return (
    <div>
      <Head>
        <title>Story Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="mt-10"
        onClick={() => {
          if (currentScreen === 3) {
            setCurrentScreen(1);
          } else {
            setCurrentScreen(currentScreen + 1);
          }
        }}
      >
        {currentScreen === 1 && (
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{
              hidden: {
                x: "100%",
                opacity: 0,
              },
              visible: {
                x: 0,
                opacity: 1,
                transition: {
                  delay: 0.5,
                  duration: 1.3,
                },
              },
            }}
          >
            <HeroSection />{" "}
          </motion.div>
        )}
        {currentScreen === 2 && <MoreAboutMe />}
        {currentScreen === 3 && (
          <div className="container mx-auto mb-20 xs:px-5 px-5 md:px-0">
            <h1 className="text-3xl font-medium mb-10 tracking-tight leading-none md:text-4xl xl:text-5xl dark:text-white">
              My Recent Blogs
            </h1>
            <div className="flex flex-wrap lg:space-x-20">
              {posts.map((post, i) => (
                <MarkdownBlogCard key={`${post}-${i}`} post={post} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const posts = getAllPosts()
    .slice(0, 9)
    .map((post) => post.meta);

  return { props: { posts } };
}

export default Home;
