import Head from "next/head";
import MarkdownBlogCard from "../components/markdown/MarkdownBlogCard";
import styles from "../styles/Home.module.css";
import { getAllPosts, PostMeta } from "../utils/markdown";

const Home = ({ posts }: { posts: PostMeta[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto mt-10">
        <h1 className="text-4xl mb-10">My Recent Blogs</h1>
        <div className="flex flex-wrap space-x-5">
          {posts.map((post, i) => (
            <MarkdownBlogCard key={`${post}-${i}`} post={post} />
          ))}
        </div>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const posts = getAllPosts()
    .slice(0, 9)
    .map((post) => post.meta);

  return { props: { posts } };
}

export default Home;
